version: 3
endpoint: http://localhost:8080
admin_secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
apply_migrations: true
apply_metadata: true
